camp = {
	['CVN_Vmax'] = 10,
	['date'] = {
		['year'] = 1986,
		['day'] = 6,
		['month'] = 11,
	},
	['MissionFilename'] = 'TF-71-Tomcat-80s_ongoing.miz',
	['idle_time_min'] = 10800,
	['dawn'] = 27900,
	['BaseAirStart'] = {
	},
	['day'] = 1,
	['CVN_despawnAfterLanding'] = true,
	['ShipHealth'] = {
		['DDG-105 Dewey'] = 100,
		['CG-47  Ticondera'] = 100,
		['Dry cargo 1'] = 100,
		['FFG-43 Hawes'] = 100,
		['FFG-57 Reuben James'] = 100,
		['Tanker 4'] = 100,
		['CG-48 Yorktown'] = 100,
		['FFG-46 Rentz'] = 100,
		['CG-67 Shiloh'] = 100,
		['CVN-74 John C. Stennis'] = 100,
		['TF-74-1'] = 100,
		['TF-71-1'] = 100,
		['DDG-106 Stockdale'] = 100,
		['FFG-36 Underwood '] = 100,
		['Tanker 2'] = 100,
		['CVN-71 Theodore Roosevelt'] = 100,
		['Tanker 3'] = 100,
		['LHA_Tarawa'] = 100,
		['FSG Molniya 952'] = 100,
		['Dry cargo 3'] = 100,
		['FFG-59 Kauffman'] = 100,
		['FFG-39 Doyle '] = 100,
		['Bulk cargo 1'] = 100,
		['FFG-28 Boone '] = 100,
		['FSG Molniya 954'] = 100,
		['FFG-38 Curts '] = 100,
		['CG-73 Port Royal'] = 100,
		['Tanker 1'] = 100,
		['FFG-48 Vandergrift'] = 100,
		['Bulk cargo 2'] = 100,
		['FSG Molniya'] = 100,
		['Dry cargo 2'] = 100,
		['LHA-Group-1'] = 100,
		['Tanker 5'] = 100,
		['FSG Molniya 953'] = 100,
	},
	['ShipMissions'] = {
		['Cargo convoy 2'] = {
			['PatrolSpeed'] = 5,
			['StartTime'] = 17514,
			['CruiseSpeed'] = 8,
			['WPtable'] = {
				[1] = {
					[1] = 'Ships 1-5',
					[2] = 'Ships 1-4',
					[4] = 'Ships 1-2',
					[3] = 'Ships 1-3',
				},
			},
		},
		['LHA-Group'] = {
			['PatrolSpeed'] = 8,
			['StartTime'] = 17514,
			['CruiseSpeed'] = 10,
			['WPtable'] = {
				[1] = {
					[1] = 'Indy 3-1',
					[2] = 'Indy 3-2',
					[4] = 'Indy 3-4',
					[3] = 'Indy 3-3',
				},
			},
		},
		['TF-74'] = {
			['PatrolSpeed'] = 8,
			['StartTime'] = 17514,
			['CruiseSpeed'] = 10,
			['WPtable'] = {
				[1] = {
					[1] = 'Indy 2-1',
					[2] = 'Indy 2-2',
					[4] = 'Indy 2-4',
					[3] = 'Indy 2-3',
				},
			},
		},
		['TF-71'] = {
			['PatrolSpeed'] = 8,
			['StartTime'] = 17514,
			['CruiseSpeed'] = 10,
			['WPtable'] = {
				[1] = {
					[1] = 'Indy 1-1',
					[2] = 'Indy 1-2',
					[4] = 'Indy 1-4',
					[3] = 'Indy 1-3',
				},
			},
		},
		['Cargo convoy 1'] = {
			['PatrolSpeed'] = 5,
			['StartTime'] = 17514,
			['CruiseSpeed'] = 8,
			['WPtable'] = {
				[1] = {
					[1] = 'Ships 1-1',
					[2] = 'Ships 1-2',
					[4] = 'Ships 1-4',
					[3] = 'Ships 1-3',
				},
			},
		},
	},
	['player'] = {
		['pack'] = {
			['Flare Illumination'] = {
			},
			['main'] = {
				[1] = {
					['number'] = 2,
					['tot_to'] = 999999,
					['eta_offset'] = 0,
					['divert'] = {
						['CVN-74 John C. Stennis'] = 'CVN-74 John C. Stennis',
					},
					['firepower'] = 2,
					['livery'] = {
						[1] = 'vf-101 grim reapers low vis',
						[2] = 'vf-101 dark',
					},
					['units'] = {
						[1] = {
							['alt'] = 0,
							['hardpoint_racks'] = true,
							['alt_type'] = 'RADIO',
							['livery_id'] = 'vf-101 red',
							['skill'] = 'Player',
							['speed'] = 1,
							['AddPropAircraft'] = {
								['LGB100'] = 6,
								['M61BURST'] = 0,
								['IlsChannel'] = 11,
								['LGB1'] = 8,
								['KY28Key'] = 1,
								['TacanBand'] = 0,
								['LGB1000'] = 1,
								['TacanChannel'] = 37,
								['LGB10'] = 8,
								['INSAlignmentStored'] = true,
								['UseLAU138'] = true,
								['ALE39Loadout'] = 3,
							},
							['type'] = 'F-14A-135-GR',
							['Radio'] = {
								[1] = {
									['channels'] = {
										[1] = 262.675,
										[2] = 393.425,
									},
								},
								[2] = {
									['channels'] = {
										[1] = 127.5,
										[2] = 385.35,
										[3] = 345.95,
										[4] = 278.85,
										[5] = 255.255,
										[6] = 281.05,
										[7] = 384.175,
									},
								},
							},
							['unitId'] = 100049,
							['psi'] = 0,
							['y'] = 346570,
							['x'] = -242459,
							['name'] = 'Pack 3 - VF-101 - Intercept 1-1',
							['payload'] = {
								['pylons'] = {
									[7] = {
										['CLSID'] = '{AIM_54A_Mk60}',
										['num'] = 7,
									},
									[1] = {
										['CLSID'] = '{LAU-138 wtip - AIM-9M}',
										['num'] = 1,
									},
									[2] = {
										['CLSID'] = '{SHOULDER AIM-7MH}',
										['num'] = 2,
									},
									[4] = {
										['CLSID'] = '{AIM_54A_Mk60}',
										['num'] = 4,
									},
									[8] = {
										['CLSID'] = '{F14-300gal}',
										['num'] = 8,
									},
									[9] = {
										['CLSID'] = '{SHOULDER AIM-7MH}',
										['num'] = 9,
									},
									[5] = {
										['CLSID'] = '{AIM_54A_Mk60}',
										['num'] = 5,
									},
									[10] = {
										['CLSID'] = '{LAU-138 wtip - AIM-9M}',
										['num'] = 10,
									},
									[3] = {
										['CLSID'] = '{F14-300gal}',
										['num'] = 3,
									},
									[6] = {
										['CLSID'] = '{AIM_54A_Mk60}',
										['num'] = 6,
									},
								},
								['fuel'] = '7348',
								['flare'] = 60,
								['chaff'] = 140,
								['gun'] = 100,
							},
							['onboard_num'] = '100',
							['heading'] = 0,
							['callsign'] = {
								[1] = 8,
								[2] = 8,
								['name'] = 'Pontiac81',
								[3] = 1,
							},
						},
						[2] = {
							['alt'] = 0,
							['hardpoint_racks'] = true,
							['alt_type'] = 'RADIO',
							['livery_id'] = 'vf-101 dark',
							['skill'] = 'High',
							['speed'] = 1,
							['AddPropAircraft'] = {
								['LGB100'] = 6,
								['M61BURST'] = 0,
								['IlsChannel'] = 11,
								['LGB1'] = 8,
								['KY28Key'] = 1,
								['TacanBand'] = 0,
								['LGB1000'] = 1,
								['TacanChannel'] = 37,
								['LGB10'] = 8,
								['INSAlignmentStored'] = true,
								['UseLAU138'] = true,
								['ALE39Loadout'] = 3,
							},
							['type'] = 'F-14A-135-GR',
							['Radio'] = {
								[1] = {
									['channels'] = {
									},
								},
								[2] = {
									['channels'] = {
									},
								},
							},
							['unitId'] = 100050,
							['psi'] = 0,
							['y'] = 346670,
							['x'] = -242359,
							['name'] = 'Pack 3 - VF-101 - Intercept 1-2',
							['payload'] = {
								['pylons'] = {
									[7] = {
										['CLSID'] = '{AIM_54A_Mk60}',
										['num'] = 7,
									},
									[1] = {
										['CLSID'] = '{LAU-138 wtip - AIM-9M}',
										['num'] = 1,
									},
									[2] = {
										['CLSID'] = '{SHOULDER AIM-7MH}',
										['num'] = 2,
									},
									[4] = {
										['CLSID'] = '{AIM_54A_Mk60}',
										['num'] = 4,
									},
									[8] = {
										['CLSID'] = '{F14-300gal}',
										['num'] = 8,
									},
									[9] = {
										['CLSID'] = '{SHOULDER AIM-7MH}',
										['num'] = 9,
									},
									[5] = {
										['CLSID'] = '{AIM_54A_Mk60}',
										['num'] = 5,
									},
									[10] = {
										['CLSID'] = '{LAU-138 wtip - AIM-9M}',
										['num'] = 10,
									},
									[3] = {
										['CLSID'] = '{F14-300gal}',
										['num'] = 3,
									},
									[6] = {
										['CLSID'] = '{AIM_54A_Mk60}',
										['num'] = 6,
									},
								},
								['fuel'] = '7348',
								['flare'] = 60,
								['chaff'] = 140,
								['gun'] = 100,
							},
							['onboard_num'] = '108',
							['heading'] = 0,
							['callsign'] = {
								[1] = 8,
								[2] = 8,
								['name'] = 'Pontiac82',
								[3] = 2,
							},
						},
					},
					['base'] = 'CVN-71 Theodore Roosevelt',
					['playable'] = true,
					['tot_from'] = 0,
					['type'] = 'F-14A-135-GR',
					['route'] = {
						[1] = {
							['eta'] = 0,
							['x'] = -242459,
							['id'] = 'Intercept',
							['y'] = 346570,
							['alt'] = 0,
						},
					},
					['country'] = 'USA',
					['airdromeId'] = 429,
					['task'] = 'Intercept',
					['loadout'] = {
						['night'] = true,
						['stores'] = {
							['pylons'] = {
								[1] = {
									['CLSID'] = '{LAU-138 wtip - AIM-9M}',
									['num'] = 1,
								},
								[2] = {
									['CLSID'] = '{SHOULDER AIM-7MH}',
									['num'] = 2,
								},
								[3] = {
									['CLSID'] = '{F14-300gal}',
									['num'] = 3,
								},
								[4] = {
									['CLSID'] = '{AIM_54A_Mk60}',
									['num'] = 4,
								},
								[5] = {
									['CLSID'] = '{AIM_54A_Mk60}',
									['num'] = 5,
								},
								[6] = {
									['CLSID'] = '{AIM_54A_Mk60}',
									['num'] = 6,
								},
								[7] = {
									['CLSID'] = '{AIM_54A_Mk60}',
									['num'] = 7,
								},
								[8] = {
									['CLSID'] = '{F14-300gal}',
									['num'] = 8,
								},
								[9] = {
									['CLSID'] = '{SHOULDER AIM-7MH}',
									['num'] = 9,
								},
								[10] = {
									['CLSID'] = '{LAU-138 wtip - AIM-9M}',
									['num'] = 10,
								},
							},
							['fuel'] = '7348',
							['flare'] = 60,
							['chaff'] = 140,
							['gun'] = 100,
						},
						['LDSD'] = true,
						['range'] = 500000,
						['capability'] = 10,
						['name'] = 'TF-Old-AIM-54A-MK60*4, AIM-7M*2, AIM-9M*2, XT*2',
						['attributes'] = {
						},
						['adverseWeather'] = true,
						['firepower'] = 1,
						['day'] = true,
						['AddPropAircraft'] = {
							['LGB100'] = 6,
							['M61BURST'] = 0,
							['IlsChannel'] = 11,
							['LGB1'] = 8,
							['KY28Key'] = 1,
							['TacanBand'] = 0,
							['ALE39Loadout'] = 3,
							['UseLAU138'] = true,
							['LGB10'] = 8,
							['INSAlignmentStored'] = true,
							['TacanChannel'] = 37,
							['LGB1000'] = 1,
						},
						['sortie_rate'] = 12,
					},
					['liveryModex'] = {
						[100] = 'vf-101 red',
						[105] = 'vf-101 grim reapers low vis',
						[111] = 'vf-101 dark',
					},
					['target'] = {
						['firepower'] = {
							['min'] = 2,
							['max'] = 4,
						},
						['radius'] = 130000,
						['attributes'] = {
						},
						['base'] = 'CVN-71 Theodore Roosevelt',
						['ATO'] = true,
						['priority'] = 10,
						['task'] = 'Intercept',
						['TitleName'] = 'CVN-71 Theodore Roosevelt Interception 2',
					},
					['player'] = true,
					['name'] = 'VF-101',
					['target_name'] = 'CVN-71 Theodore Roosevelt Interception 2',
					['callsign'] = 'Pontiac81',
					['sidenumber'] = {
						[1] = 100,
						[2] = 115,
					},
					['skill'] = 'High',
					['frequency'] = 262.675,
				},
				[2] = {
					['number'] = 2,
					['tot_to'] = 999999,
					['eta_offset'] = 0,
					['firepower'] = 2,
					['livery'] = {
						[1] = 'vf-101 grim reapers low vis',
						[2] = 'vf-101 dark',
					},
					['base'] = 'CVN-71 Theodore Roosevelt',
					['playable'] = true,
					['type'] = 'F-14A-135-GR',
					['route'] = {
						[1] = {
							['eta'] = 0,
							['x'] = -242459,
							['id'] = 'Intercept',
							['y'] = 346570,
							['alt'] = 0,
						},
					},
					['callsign'] = 'Pontiac91',
					['liveryModex'] = {
						[100] = 'vf-101 red',
						[105] = 'vf-101 grim reapers low vis',
						[111] = 'vf-101 dark',
					},
					['airdromeId'] = 429,
					['loadout'] = {
						['night'] = true,
						['stores'] = {
							['pylons'] = {
								[1] = {
									['CLSID'] = '{LAU-138 wtip - AIM-9M}',
									['num'] = 1,
								},
								[2] = {
									['CLSID'] = '{SHOULDER AIM-7MH}',
									['num'] = 2,
								},
								[3] = {
									['CLSID'] = '{F14-300gal}',
									['num'] = 3,
								},
								[4] = {
									['CLSID'] = '{AIM_54A_Mk60}',
									['num'] = 4,
								},
								[5] = {
									['CLSID'] = '{AIM_54A_Mk60}',
									['num'] = 5,
								},
								[6] = {
									['CLSID'] = '{AIM_54A_Mk60}',
									['num'] = 6,
								},
								[7] = {
									['CLSID'] = '{AIM_54A_Mk60}',
									['num'] = 7,
								},
								[8] = {
									['CLSID'] = '{F14-300gal}',
									['num'] = 8,
								},
								[9] = {
									['CLSID'] = '{SHOULDER AIM-7MH}',
									['num'] = 9,
								},
								[10] = {
									['CLSID'] = '{LAU-138 wtip - AIM-9M}',
									['num'] = 10,
								},
							},
							['fuel'] = '7348',
							['flare'] = 60,
							['chaff'] = 140,
							['gun'] = 100,
						},
						['LDSD'] = true,
						['range'] = 500000,
						['capability'] = 10,
						['name'] = 'TF-Old-AIM-54A-MK60*4, AIM-7M*2, AIM-9M*2, XT*2',
						['attributes'] = {
						},
						['adverseWeather'] = true,
						['firepower'] = 1,
						['day'] = true,
						['AddPropAircraft'] = {
							['LGB100'] = 6,
							['M61BURST'] = 0,
							['IlsChannel'] = 11,
							['LGB1'] = 8,
							['KY28Key'] = 1,
							['TacanBand'] = 0,
							['ALE39Loadout'] = 3,
							['UseLAU138'] = true,
							['LGB10'] = 8,
							['INSAlignmentStored'] = true,
							['TacanChannel'] = 37,
							['LGB1000'] = 1,
						},
						['sortie_rate'] = 12,
					},
					['sidenumber'] = {
						[1] = 100,
						[2] = 115,
					},
					['task'] = 'Intercept',
					['target'] = {
						['firepower'] = {
							['min'] = 2,
							['max'] = 4,
						},
						['radius'] = 130000,
						['attributes'] = {
						},
						['base'] = 'CVN-71 Theodore Roosevelt',
						['ATO'] = true,
						['priority'] = 10,
						['task'] = 'Intercept',
						['TitleName'] = 'CVN-71 Theodore Roosevelt Interception 2',
					},
					['name'] = 'VF-101',
					['target_name'] = 'CVN-71 Theodore Roosevelt Interception 2',
					['country'] = 'USA',
					['tot_from'] = 0,
					['skill'] = 'High',
					['frequency'] = 262.675,
				},
			},
			['Laser Illumination'] = {
			},
			['SEAD'] = {
			},
			['Escort'] = {
			},
			['Escort Jammer'] = {
			},
		},
		['side'] = 'blue',
		['waypoints'] = {
			[1] = {
				['speed_locked'] = true,
				['briefing_name'] = 'Intercept',
				['action'] = 'From Parking Area Hot',
				['alt_type'] = 'RADIO',
				['linkUnit'] = 429,
				['properties'] = {
					['vnav'] = 1,
					['scale'] = 0,
					['vangle'] = 0,
					['angle'] = 0,
					['steer'] = 2,
				},
				['helipadId'] = 429,
				['speed'] = 1,
				['task'] = {
					['id'] = 'ComboTask',
					['params'] = {
						['tasks'] = {
						},
					},
				},
				['type'] = 'TakeOffParkingHot',
				['ETA'] = 0,
				['ETA_locked'] = true,
				['y'] = 346570,
				['formation_template'] = '',
				['name'] = 'Intercept',
				['x'] = -242459,
				['alt'] = 0,
			},
		},
		['group'] = {
			['uncontrolled'] = false,
			['taskSelected'] = true,
			['modulation'] = 0,
			['groupId'] = 100051,
			['tasks'] = {
			},
			['route'] = {
				['points'] = {
					[1] = {
						['alt'] = 0,
						['briefing_name'] = 'Intercept',
						['action'] = 'From Parking Area Hot',
						['alt_type'] = 'RADIO',
						['linkUnit'] = 429,
						['properties'] = {
							['vnav'] = 1,
							['scale'] = 0,
							['angle'] = 0,
							['vangle'] = 0,
							['steer'] = 2,
						},
						['helipadId'] = 429,
						['speed'] = 1,
						['task'] = {
							['id'] = 'ComboTask',
							['params'] = {
								['tasks'] = {
									[1] = {
										['number'] = 1,
										['auto'] = false,
										['id'] = 'WrappedAction',
										['enabled'] = true,
										['params'] = {
											['action'] = {
												['id'] = 'Option',
												['params'] = {
													['value'] = 2,
													['name'] = 1,
												},
											},
										},
									},
								},
							},
						},
						['type'] = 'TakeOffParkingHot',
						['ETA'] = 0,
						['ETA_locked'] = true,
						['y'] = 2646570,
						['formation_template'] = '',
						['name'] = 'Intercept',
						['speed_locked'] = true,
						['x'] = 2057541,
					},
				},
			},
			['hidden'] = false,
			['units'] = {
				[1] = {
					['alt'] = 0,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'vf-101 red',
					['skill'] = 'Player',
					['speed'] = 1,
					['AddPropAircraft'] = {
						['LGB100'] = 6,
						['M61BURST'] = 0,
						['IlsChannel'] = 11,
						['LGB1'] = 8,
						['KY28Key'] = 1,
						['TacanBand'] = 0,
						['LGB1000'] = 1,
						['TacanChannel'] = 37,
						['LGB10'] = 8,
						['INSAlignmentStored'] = true,
						['UseLAU138'] = true,
						['ALE39Loadout'] = 3,
					},
					['type'] = 'F-14A-135-GR',
					['Radio'] = {
						[1] = {
							['channels'] = {
								[1] = 262.675,
								[2] = 393.425,
							},
						},
						[2] = {
							['channels'] = {
								[1] = 127.5,
								[2] = 385.35,
								[3] = 345.95,
								[4] = 278.85,
								[5] = 255.255,
								[6] = 281.05,
								[7] = 384.175,
							},
						},
					},
					['unitId'] = 100049,
					['psi'] = 0,
					['y'] = 346570,
					['x'] = -242459,
					['name'] = 'Pack 3 - VF-101 - Intercept 1-1',
					['payload'] = {
						['pylons'] = {
							[7] = {
								['CLSID'] = '{AIM_54A_Mk60}',
								['num'] = 7,
							},
							[1] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 1,
							},
							[2] = {
								['CLSID'] = '{SHOULDER AIM-7MH}',
								['num'] = 2,
							},
							[4] = {
								['CLSID'] = '{AIM_54A_Mk60}',
								['num'] = 4,
							},
							[8] = {
								['CLSID'] = '{F14-300gal}',
								['num'] = 8,
							},
							[9] = {
								['CLSID'] = '{SHOULDER AIM-7MH}',
								['num'] = 9,
							},
							[5] = {
								['CLSID'] = '{AIM_54A_Mk60}',
								['num'] = 5,
							},
							[10] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 10,
							},
							[3] = {
								['CLSID'] = '{F14-300gal}',
								['num'] = 3,
							},
							[6] = {
								['CLSID'] = '{AIM_54A_Mk60}',
								['num'] = 6,
							},
						},
						['fuel'] = '7348',
						['flare'] = 60,
						['chaff'] = 140,
						['gun'] = 100,
					},
					['onboard_num'] = '100',
					['heading'] = 0,
					['callsign'] = {
						[1] = 8,
						[2] = 8,
						['name'] = 'Pontiac81',
						[3] = 1,
					},
				},
				[2] = {
					['alt'] = 0,
					['hardpoint_racks'] = true,
					['alt_type'] = 'RADIO',
					['livery_id'] = 'vf-101 dark',
					['skill'] = 'High',
					['speed'] = 1,
					['AddPropAircraft'] = {
						['LGB100'] = 6,
						['M61BURST'] = 0,
						['IlsChannel'] = 11,
						['LGB1'] = 8,
						['KY28Key'] = 1,
						['TacanBand'] = 0,
						['LGB1000'] = 1,
						['TacanChannel'] = 37,
						['LGB10'] = 8,
						['INSAlignmentStored'] = true,
						['UseLAU138'] = true,
						['ALE39Loadout'] = 3,
					},
					['type'] = 'F-14A-135-GR',
					['Radio'] = {
						[1] = {
							['channels'] = {
							},
						},
						[2] = {
							['channels'] = {
							},
						},
					},
					['unitId'] = 100050,
					['psi'] = 0,
					['y'] = 346670,
					['x'] = -242359,
					['name'] = 'Pack 3 - VF-101 - Intercept 1-2',
					['payload'] = {
						['pylons'] = {
							[7] = {
								['CLSID'] = '{AIM_54A_Mk60}',
								['num'] = 7,
							},
							[1] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 1,
							},
							[2] = {
								['CLSID'] = '{SHOULDER AIM-7MH}',
								['num'] = 2,
							},
							[4] = {
								['CLSID'] = '{AIM_54A_Mk60}',
								['num'] = 4,
							},
							[8] = {
								['CLSID'] = '{F14-300gal}',
								['num'] = 8,
							},
							[9] = {
								['CLSID'] = '{SHOULDER AIM-7MH}',
								['num'] = 9,
							},
							[5] = {
								['CLSID'] = '{AIM_54A_Mk60}',
								['num'] = 5,
							},
							[10] = {
								['CLSID'] = '{LAU-138 wtip - AIM-9M}',
								['num'] = 10,
							},
							[3] = {
								['CLSID'] = '{F14-300gal}',
								['num'] = 3,
							},
							[6] = {
								['CLSID'] = '{AIM_54A_Mk60}',
								['num'] = 6,
							},
						},
						['fuel'] = '7348',
						['flare'] = 60,
						['chaff'] = 140,
						['gun'] = 100,
					},
					['onboard_num'] = '108',
					['heading'] = 0,
					['callsign'] = {
						[1] = 8,
						[2] = 8,
						['name'] = 'Pontiac82',
						[3] = 2,
					},
				},
			},
			['y'] = 346570,
			['radioSet'] = true,
			['name'] = 'Pack 3 - VF-101 - Intercept 1',
			['communication'] = true,
			['x'] = -242459,
			['start_time'] = 0,
			['task'] = 'Intercept',
			['frequency'] = 262.675,
		},
		['flight'] = 1,
		['tgt_side'] = 'red',
		['role'] = 'main',
		['airbase'] = 'CVN-71 Theodore Roosevelt',
		['unitname'] = 'F-14A-135-GR Pack 3 - VF-101 - Intercept 1-1',
		['pack_n'] = 3,
		['tgt_pack'] = 6,
		['tgt_wp'] = 1,
		['target'] = {
			['firepower'] = {
				['min'] = 2,
				['max'] = 4,
			},
			['radius'] = 130000,
			['attributes'] = {
			},
			['task'] = 'Intercept',
			['ATO'] = true,
			['priority'] = 10,
			['base'] = 'CVN-71 Theodore Roosevelt',
			['TitleName'] = 'CVN-71 Theodore Roosevelt Interception 2',
		},
	},
	['title'] = 'TF-71-Tomcat-80s',
	['aircraft_availability'] = {
		['VFA-106'] = {
			['assigned'] = 7,
			['available'] = 7,
			['unassigned'] = 0,
			['unavailable'] = {
				[7] = 43539,
				[1] = 50739,
				[2] = 50739,
				[8] = 0,
				[5] = 43539,
				[3] = 50739,
				[6] = 43539,
				[4] = 43539,
			},
			['serviceable'] = 7,
			['ready'] = 8,
		},
		['VF-143'] = {
			['assigned'] = 6,
			['available'] = 14,
			['unassigned'] = 8,
			['unavailable'] = {
				[11] = 0,
				[13] = 0,
				[7] = 0,
				[1] = 43539,
				[2] = 43539,
				[15] = 0,
				[8] = 0,
				[16] = 0,
				[9] = 0,
				[5] = 39939,
				[10] = 0,
				[14] = 0,
				[3] = 43539,
				[6] = 39939,
				[12] = 0,
				[4] = 43539,
			},
			['serviceable'] = 14,
			['ready'] = 16,
		},
		['174 ARW'] = {
			['assigned'] = 4,
			['available'] = 11,
			['unassigned'] = 7,
			['unavailable'] = {
				[7] = 0,
				[1] = 43539,
				[2] = 43539,
				[4] = 32739,
				[8] = 0,
				[9] = 0,
				[5] = 0,
				[10] = 0,
				[3] = 32739,
				[6] = 0,
				[12] = 0,
				[11] = 0,
			},
			['serviceable'] = 11,
			['ready'] = 12,
		},
		['52.TBAP'] = {
			['assigned'] = 6,
			['available'] = 6,
			['unassigned'] = 0,
			['unavailable'] = {
				[6] = 50739,
				[2] = 50739,
				[3] = 50739,
				[1] = 50739,
				[4] = 50739,
				[5] = 50739,
			},
			['serviceable'] = 6,
			['ready'] = 6,
		},
		['368.ShAP'] = {
			['assigned'] = 0,
			['available'] = 17,
			['unassigned'] = 17,
			['unavailable'] = {
				[1] = 0,
				[2] = 0,
				[4] = 0,
				[8] = 0,
				[16] = 0,
				[17] = 0,
				[9] = 0,
				[18] = 0,
				[5] = 0,
				[10] = 0,
				[20] = 0,
				[21] = 0,
				[11] = 0,
				[22] = 0,
				[3] = 0,
				[6] = 0,
				[12] = 0,
				[24] = 0,
				[13] = 0,
				[7] = 0,
				[14] = 0,
				[15] = 0,
				[19] = 0,
				[23] = 0,
			},
			['serviceable'] = 17,
			['ready'] = 24,
		},
		['VAW-125'] = {
			['assigned'] = 2,
			['available'] = 5,
			['unassigned'] = 3,
			['unavailable'] = {
				[6] = 0,
				[2] = 29139,
				[8] = 0,
				[3] = 0,
				[1] = 43539,
				[4] = 0,
				[5] = 0,
				[7] = 0,
			},
			['serviceable'] = 5,
			['ready'] = 8,
		},
		['VMFA-312'] = {
			['assigned'] = 10,
			['available'] = 11,
			['unassigned'] = 1,
			['unavailable'] = {
				[11] = 0,
				[13] = 0,
				[7] = 50739,
				[1] = 50739,
				[2] = 50739,
				[8] = 50739,
				[9] = 50739,
				[5] = 50739,
				[10] = 50739,
				[3] = 50739,
				[6] = 50739,
				[12] = 0,
				[4] = 50739,
			},
			['serviceable'] = 11,
			['ready'] = 13,
		},
		['174.IAP-PVO'] = {
			['assigned'] = 3,
			['available'] = 3,
			['unassigned'] = 0,
			['unavailable'] = {
				[2] = 50739,
				[3] = 50739,
				[1] = 50739,
				[4] = 0,
			},
			['serviceable'] = 3,
			['ready'] = 4,
		},
		['19.IAP'] = {
			['assigned'] = 4,
			['available'] = 9,
			['unassigned'] = 5,
			['unavailable'] = {
				[7] = 0,
				[1] = 50739,
				[2] = 50739,
				[4] = 50739,
				[8] = 0,
				[9] = 0,
				[5] = 0,
				[10] = 0,
				[3] = 50739,
				[6] = 0,
			},
			['serviceable'] = 9,
			['ready'] = 10,
		},
		['3.IAP'] = {
			['assigned'] = 0,
			['available'] = 7,
			['unassigned'] = 7,
			['unavailable'] = {
				[7] = 0,
				[1] = 0,
				[2] = 0,
				[4] = 0,
				[8] = 0,
				[9] = 0,
				[5] = 0,
				[3] = 0,
				[6] = 0,
			},
			['serviceable'] = 7,
			['ready'] = 9,
		},
		['175 ARW'] = {
			['assigned'] = 0,
			['available'] = 11,
			['unassigned'] = 11,
			['unavailable'] = {
				[7] = 0,
				[1] = 0,
				[2] = 0,
				[4] = 0,
				[8] = 0,
				[9] = 0,
				[5] = 0,
				[10] = 0,
				[3] = 0,
				[6] = 0,
				[11] = 0,
			},
			['serviceable'] = 11,
			['ready'] = 11,
		},
		['31.IAP'] = {
			['assigned'] = 4,
			['available'] = 9,
			['unassigned'] = 5,
			['unavailable'] = {
				[7] = 0,
				[1] = 50739,
				[2] = 50739,
				[4] = 50739,
				[8] = 0,
				[9] = 0,
				[5] = 0,
				[10] = 0,
				[3] = 50739,
				[6] = 0,
				[12] = 0,
				[11] = 0,
			},
			['serviceable'] = 9,
			['ready'] = 12,
		},
		['79.TBAP'] = {
			['assigned'] = 0,
			['available'] = 1,
			['unassigned'] = 1,
			['unavailable'] = {
				[2] = 0,
				[1] = 0,
			},
			['serviceable'] = 1,
			['ready'] = 2,
		},
		['959.BAP'] = {
			['assigned'] = 4,
			['available'] = 4,
			['unassigned'] = 0,
			['unavailable'] = {
				[7] = 0,
				[1] = 50739,
				[2] = 50739,
				[4] = 50739,
				[8] = 0,
				[5] = 0,
				[3] = 50739,
				[6] = 0,
			},
			['serviceable'] = 4,
			['ready'] = 8,
		},
		['28.IAP'] = {
			['assigned'] = 5,
			['available'] = 5,
			['unassigned'] = 0,
			['unavailable'] = {
				[1] = 50739,
				[2] = 50739,
				[4] = 48939,
				[5] = 48939,
				[3] = 50739,
				[6] = 0,
			},
			['serviceable'] = 5,
			['ready'] = 6,
		},
		['11.RAP'] = {
			['assigned'] = 0,
			['available'] = 2,
			['unassigned'] = 2,
			['unavailable'] = {
				[2] = 0,
				[3] = 0,
				[1] = 0,
				[4] = 0,
			},
			['serviceable'] = 2,
			['ready'] = 4,
		},
		['VF-101'] = {
			['assigned'] = 6,
			['available'] = 10,
			['unassigned'] = 4,
			['unavailable'] = {
				[11] = 0,
				[13] = 0,
				[7] = 0,
				[1] = 47139,
				[2] = 47139,
				[8] = 0,
				[9] = 0,
				[5] = 43539,
				[10] = 0,
				[3] = 43539,
				[6] = 43539,
				[12] = 0,
				[4] = 43539,
			},
			['serviceable'] = 10,
			['ready'] = 13,
		},
		['559.BAP'] = {
			['assigned'] = 8,
			['available'] = 8,
			['unassigned'] = 0,
			['unavailable'] = {
				[7] = 50739,
				[1] = 50739,
				[2] = 50739,
				[4] = 50739,
				[8] = 50739,
				[9] = 0,
				[5] = 50739,
				[3] = 50739,
				[6] = 50739,
			},
			['serviceable'] = 8,
			['ready'] = 9,
		},
	},
	['mission'] = 2,
	['path'] = 'C:/Users/marco/Saved Games/DCS/',
	['startup'] = 600,
	['SC_CarrierIntoWind'] = 'man',
	['idle_time_max'] = 14400,
	['time'] = 36339,
	['ShipDamagedLast'] = {
	},
	['weather'] = {
		['zoneNextTemp'] = 11,
		['pHigh'] = 25,
		['pLow'] = 75,
		['zoneNext'] = 'high',
		['zoneTemp'] = 13,
		['refTemp'] = 10,
		['zoneEnd'] = 167840,
		['zoneStart'] = -1,
		['zone'] = 'high',
	},
	['CVN_windDeck'] = 9,
	['dusk'] = 65700,
	['radio'] = {
		['blue'] = {
			[1] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 399,
				},
				['FM'] = {
					['min'] = 30,
					['max'] = 87,
				},
				['VHF'] = {
					['min'] = 118,
					['max'] = 173,
				},
			},
			[2] = {
				['FM'] = {
					['min'] = 30,
					['max'] = 87,
				},
				['UHF'] = {
					['min'] = 225,
					['max'] = 399,
				},
				['VHF'] = {
					['min'] = 118,
					['max'] = 173,
				},
			},
		},
		['red'] = {
			[1] = {
				['UHF'] = {
					['min'] = 225,
					['max'] = 390,
				},
				['VHF'] = {
					['min'] = 118,
					['max'] = 224.995,
				},
			},
		},
	},
	['versionPackageICM'] = 'NG',
	['MultiPlayer'] = {
		['pack_n'] = {
		},
	},
	['units'] = 'imperial',
	['debug'] = false,
	['pedro'] = {
		['LHA_Tarawa'] = {
			['bearing_from_leader_BaseMiss'] = 291.75651026227,
			['distance_from_leader'] = 71.744488792048,
		},
		['CVN-71 Theodore Roosevelt'] = {
			['bearing_from_leader_BaseMiss'] = 295.14567530467,
			['distance_from_leader'] = 90.292944244149,
		},
		['CVN-74 John C. Stennis'] = {
			['bearing_from_leader_BaseMiss'] = 295.53127903844,
			['distance_from_leader'] = 85.544967226995,
		},
	},
	['mission_duration'] = 5400,
	['version'] = 'V5.0o',
	['ScriptsMod'] = '20.47.105',
	['flag'] = {
	},
	['variation'] = 4,
	['ShipHealth0'] = {
		['DDG-105 Dewey'] = 2100,
		['CG-47  Ticondera'] = 2700,
		['Dry cargo 1'] = 200,
		['FFG-43 Hawes'] = 2100,
		['FFG-57 Reuben James'] = 2100,
		['Tanker 4'] = 400,
		['CG-48 Yorktown'] = 2700,
		['FFG-46 Rentz'] = 2100,
		['CG-67 Shiloh'] = 2700,
		['CVN-74 John C. Stennis'] = 7300,
		['TF-74-1'] = 1000,
		['TF-71-1'] = 1000,
		['DDG-106 Stockdale'] = 2100,
		['FFG-36 Underwood '] = 2100,
		['Tanker 2'] = 400,
		['CVN-71 Theodore Roosevelt'] = 7300,
		['Tanker 3'] = 400,
		['LHA_Tarawa'] = 7300,
		['FSG Molniya 952'] = 700,
		['Dry cargo 3'] = 200,
		['FFG-59 Kauffman'] = 2100,
		['FFG-39 Doyle '] = 2100,
		['Bulk cargo 1'] = 200,
		['FFG-28 Boone '] = 2100,
		['FSG Molniya 954'] = 700,
		['FFG-38 Curts '] = 2100,
		['CG-73 Port Royal'] = 2700,
		['Tanker 1'] = 400,
		['FFG-48 Vandergrift'] = 2100,
		['Bulk cargo 2'] = 200,
		['FSG Molniya'] = 700,
		['Dry cargo 2'] = 200,
		['LHA-Group-1'] = 1000,
		['Tanker 5'] = 400,
		['FSG Molniya 953'] = 700,
	},
}
