oob_air = {
	['blue'] = {
		[1] = {
			['number'] = 28,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 25,
			},
			['name'] = 'R/VMFA-312',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[2] = {
			['number'] = 16,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 8,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[100] = 'vf-101 red',
				[105] = 'vf-101 grim reapers low vis',
				[111] = 'vf-101 dark',
			},
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['player'] = true,
			['name'] = 'VF-101',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 5,
				['kills_ship'] = 0,
				['kills_air'] = 8,
				['ready'] = 5,
			},
			['livery'] = {
				[1] = 'vf-101 grim reapers low vis',
				[2] = 'vf-101 dark',
			},
			['roster'] = {
				['lost'] = 5,
				['damaged'] = 0,
				['ready'] = 13,
			},
			['base'] = 'CVN-71 Theodore Roosevelt',
			['sidenumber'] = {
				[1] = 100,
				[2] = 115,
			},
		},
		[3] = {
			['number'] = 12,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 430,
				[2] = 450,
			},
			['roster'] = {
				['lost'] = 1,
				['damaged'] = 0,
				['ready'] = 11,
			},
			['name'] = '175 ARW',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 1,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 1,
			},
		},
		[4] = {
			['number'] = 16,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 2,
				['kills_ground'] = 9,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = true,
				['CAP'] = true,
				['Intercept'] = false,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[200] = 'vfa-106 high visibility',
			},
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['Anti-ship Strike'] = 2,
				['CAP'] = 0.2,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = 'VFA-106',
			['score_last'] = {
				['kills_ground'] = 9,
				['damaged'] = 0,
				['lost'] = 10,
				['kills_ship'] = 0,
				['kills_air'] = 2,
				['ready'] = 10,
			},
			['livery'] = 'vfa-106',
			['roster'] = {
				['lost'] = 10,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['base'] = 'CVN-71 Theodore Roosevelt',
			['sidenumber'] = {
				[1] = 200,
				[2] = 215,
			},
		},
		[5] = {
			['number'] = 4,
			['type'] = 'AV8BNA',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = false,
			},
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[100] = 'vma-311d',
			},
			['tasksCoef'] = {
				['Strike'] = 3,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 2,
				['CAP'] = 0.2,
				['Intercept'] = 1,
			},
			['inactive'] = true,
			['name'] = 'VMA 311',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['livery'] = 'vma-311',
			['sidenumber'] = {
				[1] = 100,
				[2] = 103,
			},
			['base'] = 'LHA_Tarawa',
			['player'] = false,
		},
		[6] = {
			['number'] = 8,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 600,
				[2] = 609,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = 'VAW-125',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[7] = {
			['number'] = 16,
			['type'] = 'F-14A-135-GR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 7,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = false,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[100] = 'vf-143 pukin dogs cag',
				[110] = 'vf-143 pukin dogs low vis (1995)',
				[114] = 'vf-143 pukin dogs low vis',
			},
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = 'VF-143',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 2,
				['kills_ship'] = 0,
				['kills_air'] = 7,
				['ready'] = 2,
			},
			['livery'] = {
				[1] = 'vf-143 pukin dogs low vis',
				[2] = 'vf-143 pukin dogs low vis (1995)',
			},
			['roster'] = {
				['lost'] = 2,
				['damaged'] = 0,
				['ready'] = 16,
			},
			['base'] = 'CVN-74 John C. Stennis',
			['sidenumber'] = {
				[1] = 100,
				[2] = 115,
			},
		},
		[8] = {
			['number'] = 10,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/174 ARW',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 9,
			},
		},
		[9] = {
			['number'] = 1,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/VAW-125',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
		},
		[10] = {
			['number'] = 30,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['name'] = 'R/VF-143',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[11] = {
			['number'] = 16,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 8,
				['kills_ground'] = 8,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['SEAD'] = true,
				['Anti-ship Strike'] = false,
				['CAP'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[200] = 'vmfa-312 high visibility',
			},
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['Anti-ship Strike'] = 2,
				['CAP'] = 0.2,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = 'VMFA-312',
			['score_last'] = {
				['kills_ground'] = 8,
				['damaged'] = 0,
				['lost'] = 6,
				['kills_ship'] = 0,
				['kills_air'] = 8,
				['ready'] = 6,
			},
			['livery'] = 'vmfa-312',
			['roster'] = {
				['lost'] = 6,
				['damaged'] = 0,
				['ready'] = 13,
			},
			['base'] = 'CVN-74 John C. Stennis',
			['sidenumber'] = {
				[1] = 200,
				[2] = 215,
			},
		},
		[12] = {
			['number'] = 30,
			['type'] = 'AV8BNA',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['name'] = 'VMA 331',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[13] = {
			['number'] = 24,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 22,
			},
			['name'] = 'R/VF-101',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[14] = {
			['number'] = 28,
			['type'] = 'F/A-18C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 26,
			},
			['name'] = 'R/VFA-106',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[15] = {
			['number'] = 12,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 400,
				[2] = 429,
			},
			['roster'] = {
				['lost'] = 1,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '174 ARW',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 1,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 1,
			},
		},
	},
	['red'] = {
		[1] = {
			['number'] = 6,
			['type'] = 'Tu-142',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 600,
				[2] = 645,
			},
			['roster'] = {
				['lost'] = 5,
				['damaged'] = 0,
				['ready'] = 2,
			},
			['name'] = '79.TBAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Tbilissi-Lochini',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 5,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 5,
			},
		},
		[2] = {
			['number'] = 6,
			['type'] = 'Tu-22M3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 600,
				[2] = 645,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '52.TBAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Mineralnye-Vody',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[3] = {
			['number'] = 24,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 23,
			},
			['name'] = 'R/3.IAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[4] = {
			['number'] = 24,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 20,
			},
			['name'] = 'R/959.BAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[5] = {
			['number'] = 6,
			['type'] = 'MiG-25PD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 2,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = false,
				['Intercept'] = true,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 200,
				[2] = 245,
			},
			['roster'] = {
				['lost'] = 3,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '174.IAP-PVO',
			['livery'] = {
				[1] = 'af standard',
			},
			['base'] = 'Mozdok',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 3,
				['kills_ship'] = 0,
				['kills_air'] = 2,
				['ready'] = 3,
			},
		},
		[6] = {
			['number'] = 12,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
				['SEAD'] = false,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 420,
				[2] = 445,
			},
			['roster'] = {
				['lost'] = 8,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '959.BAP',
			['livery'] = 'af standard',
			['base'] = 'Kutaisi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 8,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 8,
			},
		},
		[7] = {
			['number'] = 24,
			['type'] = 'MiG-25PD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 23,
			},
			['name'] = 'R/174.IAP-PVO',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[8] = {
			['number'] = 24,
			['type'] = 'Su-17M4',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/368.ShAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[9] = {
			['number'] = 6,
			['type'] = 'Su-24MR',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Reconnaissance'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 400,
				[2] = 410,
			},
			['roster'] = {
				['lost'] = 2,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '11.RAP',
			['livery'] = 'af standard',
			['base'] = 'Maykop-Khanskaya',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 2,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 2,
			},
		},
		[10] = {
			['number'] = 12,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
				['SEAD'] = false,
				['Laser Illumination'] = false,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 350,
				[2] = 385,
			},
			['roster'] = {
				['lost'] = 7,
				['damaged'] = 0,
				['ready'] = 9,
			},
			['name'] = '559.BAP',
			['livery'] = 'af standard',
			['base'] = 'Senaki-Kolkhi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 7,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 7,
			},
		},
		[11] = {
			['number'] = 10,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 3,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 10,
				[2] = 45,
			},
			['roster'] = {
				['lost'] = 4,
				['damaged'] = 0,
				['ready'] = 10,
			},
			['name'] = '19.IAP',
			['livery'] = {
				[1] = 'VVS - AMT-11 Grey',
			},
			['base'] = 'Batumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 4,
				['kills_ship'] = 0,
				['kills_air'] = 3,
				['ready'] = 4,
			},
		},
		[12] = {
			['number'] = 24,
			['type'] = 'Tu-22M3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/52.TBAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[13] = {
			['number'] = 24,
			['type'] = 'Tu-142',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 23,
			},
			['name'] = 'R/79.TBAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[14] = {
			['number'] = 18,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 14,
			},
			['name'] = 'R/559.BAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[15] = {
			['number'] = 12,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 150,
				[2] = 195,
			},
			['roster'] = {
				['lost'] = 4,
				['damaged'] = 0,
				['ready'] = 9,
			},
			['name'] = '3.IAP',
			['livery'] = 'af standard',
			['base'] = 'Kutaisi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 4,
				['kills_ship'] = 0,
				['kills_air'] = 1,
				['ready'] = 4,
			},
		},
		[16] = {
			['number'] = 24,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 22,
			},
			['name'] = 'R/28.IAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[17] = {
			['number'] = 12,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 50,
				[2] = 95,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '31.IAP',
			['livery'] = 'af standard',
			['base'] = 'Sukhumi',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[18] = {
			['number'] = 12,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 100,
				[2] = 145,
			},
			['roster'] = {
				['lost'] = 8,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '28.IAP',
			['livery'] = 'VVS - AMT-11 Grey',
			['base'] = 'Gudauta',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 8,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 8,
			},
		},
		[19] = {
			['number'] = 24,
			['type'] = 'MiG-21Bis',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 20,
			},
			['name'] = 'R/19.IAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[20] = {
			['number'] = 24,
			['type'] = 'Su-17M4',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = false,
				['Anti-ship Strike'] = true,
				['SEAD'] = false,
			},
			['skill'] = 'Random',
			['sidenumber'] = {
				[1] = 300,
				[2] = 345,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '368.ShAP',
			['livery'] = 'af standard (worn-out)',
			['base'] = 'Kobuleti',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
		},
		[21] = {
			['number'] = 24,
			['type'] = 'MiG-23MLD',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/31.IAP',
			['score_last'] = {
				['kills_ground'] = 0,
				['damaged'] = 0,
				['lost'] = 0,
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['ready'] = 0,
			},
			['base'] = 'Reserves',
			['inactive'] = true,
		},
	},
}
TypeAlias = {
}
