report_commander = {
	[1] = {
		['target_priority'] = {
			['blue'] = {
				['209 SA-2 Site R-3'] = 6,
				['Bridge Vladikavkaz MN 76'] = 3,
				['Mozdok airbase OCA Strike'] = 1,
				['Bridge South Beslan MN 68'] = 3,
				['Bridge Vladikavkaz South MN 76'] = 3,
				['High priority Target BESLAN FARP SUPPLY LINE B'] = 6,
				['TSKHINVALI FARP AA'] = 2,
				['CAP Tbilissi'] = 20,
				['High priority Target Prohladniy Depot MP 24 SUPPLY LINE A'] = 6,
				['AWACS'] = 10,
				['Tanker Track East'] = 10,
				['CHERKESSK SUPPLY PLANT KP69'] = 4,
				['Rail Bridge Kardzhin MN 49'] = 3,
				['503 5th Artillery Division/3.Btry'] = 1,
				['502 5th Artillery Division/2.Btry'] = 1,
				['LENIGORI FARP MM56'] = 6,
				['Sweep West'] = 1,
				['High priority Target Prohladniy Depot MP 24 SUPPLY LINE B'] = 6,
				['NOVOROSSIYSK SA-2 Site DK-04'] = 4,
				['106 SA-2 Site C-6'] = 6,
				['Vaziani Alert'] = 5,
				['LENIGORI FARP AA'] = 2,
				['Sweep Center'] = 1,
				['BESLAN-NOGIR FARP SUPPLY LINE'] = 1,
				['501 5th Artillery Division/1.Btry'] = 1,
				['Teberda SA-2 Site'] = 6,
				['Nalchik airbase OCA Strike'] = 1,
				['CAP Kutaisi'] = 20,
				['Kutaisi Alert 100'] = 7,
				['CVN-71 Theodore Roosevelt Alert'] = 7,
				['Mineralnye-Vody airbase OCA Strike'] = 1,
				['Battle Group AEW'] = 10,
				['Maykop SA-2'] = 4,
				['101 EWR Site'] = 5,
				['104 SA-6 Site E-4'] = 6,
				['High priority Target BESLAN FARP SUPPLY LINE A'] = 6,
				['Mineralnye-Vody Airbase'] = 3,
				['Mozdok Airbase'] = 3,
				['Kutaisi Alert'] = 5,
				['Bridge Vladikavkaz North MN 76'] = 3,
				['103 EWR Site'] = 5,
				['Maykop-Khanskaya Airbase'] = 3,
				['BAKSAN-MOZDOK SUPPLY LINE'] = 2,
				['Beslan Airbase'] = 4,
				['Rail Bridge SE Mayskiy MP 23'] = 3,
				['504 5th Artillery Division/4.Btry'] = 1,
				['Rail Bridge SW Kardzhin MN 49'] = 3,
				['Bridge SW Kardzhin MN 49'] = 3,
				['NKRYMSK SA-5 Site DK-17'] = 4,
				['TSKHINVALI FARP MM27'] = 6,
				['BESLAN-TSKHINVALI FARP SUPPLY LINE'] = 1,
				['High priority Target Rail Bridge Digora MN 38'] = 6,
				['Nalchik Airbase'] = 3,
				['NOGIR FARP MN76'] = 6,
				['Bridge Alagir MN 36'] = 3,
				['Russian Convoy 1'] = 1,
				['407 8th Army ELINT Station'] = 6,
				['101 SA-3 Site E-1'] = 6,
				['Recovery Tanker'] = 5,
				['BAKSAN-MINERALNYE SUPPLY LINE'] = 4,
				['BESLAN-LENIGORI FARP SUPPLY LINE'] = 1,
				['Peredovaya SUPPLY PLANT'] = 4,
				['Bridge South Elhotovo MN 39'] = 3,
				['206 SA-2 Site B-3'] = 6,
				['Mission Support Tanker'] = 10,
				['High priority Target BESLAN FARP SUPPLY LINE C'] = 6,
				['Russian Convoy 2'] = 1,
				['Prohladniy Depot MP 24-BESLAN SUPPLY LINE'] = 1,
				['SUPPLY PLANT BAKSAN LP83'] = 4,
				['203 SA-2 Site A-3'] = 6,
				['Prohladniy Depot MP 24'] = 4,
				['Beslan Airbase OCA Strike'] = 1,
				['High priority Target Prohladniy Depot MP 24 SUPPLY LINE C'] = 6,
				['102 EWR Site'] = 5,
				['Rail Bridge Digora MN 38'] = 3,
				['Sweep East'] = 1,
				['DM-34 SA-5 Site-1'] = 6,
				['204 SA-6 Site B-1'] = 6,
				['Battle Group CAP'] = 10,
				['Tanker Track West'] = 10,
			},
			['red'] = {
				['Rapier Site bridge Vartsihe Geguti'] = 6,
				['KHASHURI FARP AA'] = 2,
				['AMBROLAURI FARP LN41'] = 6,
				['LHA-Group'] = 1,
				['Bridge Anaklia-GG19'] = 2,
				['EWR-1 Site'] = 5,
				['CAP AWACS'] = 10,
				['AWACS'] = 10,
				['SUPPLY PLANT MARNEULI ML89'] = 4,
				['Nalchik Alert 200 Km'] = 7,
				['Bridge Orsantia-GH10'] = 2,
				['bridge TKIBULI'] = 6,
				['AMBROLAURI FARP AA'] = 2,
				['SUPPLY PLANT DAPNARI KM76'] = 4,
				['CAP Mozdok'] = 20,
				['Tbilisi Defenses'] = 2,
				['Nalchik Alert 100 Km'] = 6,
				['Rapier Site Tabakhmela'] = 6,
				['Mozdok Alert 200 Km'] = 5,
				['Bridge Koki-GH20'] = 6,
				['Bridge Kutaisi-LM18'] = 6,
				['Vaziani Defenses'] = 2,
				['16 1st Artillery Division/6.Btry'] = 1,
				['Senaki Defenses'] = 2,
				['18 1st Artillery Division/8.Btry'] = 1,
				['CAP Mineralnye-Vody'] = 7,
				['12 1st Artillery Division/2.Btry'] = 1,
				['11 1st Artillery Division/1.Btry'] = 1,
				['14 1st Artillery Division/4.Btry'] = 1,
				['13 1st Artillery Division/3.Btry'] = 1,
				['EWR-2 Site'] = 5,
				['Hawk Site Kutaisi'] = 6,
				['Bridge Geguti-LM17'] = 6,
				['Mozdok Alert 120 Km'] = 7,
				['Gudauta Train Station - FH37'] = 1,
				['Kutaisi Defenses'] = 2,
				['Mineralnye-Vody Alert 280 Km'] = 4,
				['Rail Bridge Tagiloni-GH21'] = 6,
				['CAP Center'] = 7,
				['Sukhumi OCA Strike'] = 1,
				['EWR-3 Site'] = 5,
				['Bridge Dapnari-KM76'] = 6,
				['Rail Bridge Patara-Poti-GG27'] = 2,
				['Bridge Patara-Poti West-GG27'] = 1,
				['Batumi Air Defenses'] = 2,
				['Bridge Patara-Poti East-GG27'] = 2,
				['Bridge Rike-GH31'] = 4,
				['10 US Army ELINT Station'] = 5,
				['19 4th Army HQ'] = 6,
				['bridge GORI'] = 6,
				['Tbilissi Airbase'] = 2,
				['CAP Nalchik'] = 6,
				['Kobuleti Airbase'] = 2,
				['Bzyb Train Station - FH18'] = 1,
				['Bridge Pahulani-GH42'] = 2,
				['Kutaisi Airbase'] = 4,
				['Rail Bridge North Geguti-LM17'] = 6,
				['15 1st Artillery Division/5.Btry'] = 1,
				['NATO Convoy 1'] = 1,
				['Sukhumi Airbase'] = 4,
				['Airlift Mineralnye-Vody'] = 1,
				['Tbilissi-Lochini OCA Strike'] = 1,
				['KHASHURI FARP LM84'] = 6,
				['Senaki Airbase'] = 1,
				['Sukhumi-Babushara Train Station - FH74'] = 1,
				['CVN-71 Theodore Roosevelt'] = 1,
				['Adzhkhahara Train Station - FH28'] = 1,
				['GORI AA'] = 2,
				['Sukhumi Defenses'] = 2,
				['Rail Bridge Dapnari-KM76'] = 6,
				['Bridge Supply Line Gori - Tbilisi'] = 6,
				['Batumi Airbase'] = 2,
				['Vaziani OCA Strike'] = 1,
				['Airlift Beslan'] = 1,
				['Sukhumi Train Station - FH66'] = 1,
				['Bridge Vartsihe-LM16'] = 6,
				['Leselidze Train Station - EJ80'] = 1,
				['Senaki-Kolkhi Train Station - KM58'] = 2,
				['Kvemo-Merheuli Train Station - FH66'] = 1,
				['Gudauta Airbase'] = 1,
				['Beslan Alert 120 Km'] = 7,
				['Novyy Afon Train Station - FH57'] = 1,
				['Senaki-Kolkhi OCA Strike'] = 1,
				['Kutaisi OCA Strike'] = 1,
				['Kobuleti Defenses'] = 2,
				['Mineralnye-Vody Alert 200 Km'] = 5,
				['CAP Beslan'] = 10,
				['GORI FARP MM25'] = 6,
				['Sukhumi Airbase Strategics'] = 4,
				['Gumista Train Station - FH56'] = 1,
				['17 1st Artillery Division/7.Btry'] = 1,
				['CVN-74 John C. Stennis'] = 1,
				['Kobuleti Train Station - GG44'] = 2,
				['Bridge Supply Line Marneuli - Tbilisi'] = 6,
				['Sweep South'] = 1,
			},
		},
		['config_module'] = {
			['ATO_Generator'] = {
				['blue'] = {
					['UNIT_SERVICEABILITY'] = 0.8,
					['MIN_PERCENTAGE_FOR_ESCORT'] = 0.75,
					['FACTOR_FOR_REDUCTION_AIR_THREAT'] = 0.5,
					['MULTIPLIER_TARGET_DISTANCE_FOR_EVALUTATION_UNIT_RANGE_LOADOUT'] = 2,
					['WEIGHT_SCORE_FOR_AIRCRAFT_COST'] = {
						['Fighter'] = 0.3,
						['Refueler'] = 0.1,
						['Bomber'] = 0.2,
						['Transporter'] = 0.1,
						['AWACS'] = 0.1,
						['Reco'] = 0.2,
						['Attacker'] = 0.5,
						['Helicopter'] = 0.2,
					},
					['MAX_AIRCRAFT_FOR_STRIKE'] = 4,
					['WEIGHT_SCORE_FOR_LOADOUT_COST'] = {
						['Strike'] = 0.3,
						['Anti-ship Strike'] = 0.1,
						['Escort'] = 0.3,
						['Reconnaissance'] = 0.1,
						['SEAD'] = 0.1,
						['CAP'] = 0.4,
						['Fighter Sweep'] = 0.2,
						['Intercept'] = 0.2,
					},
					['MIN_TOTAL_AIR_THREAT_FOR_ESCORT_SUPPORT'] = 0.5,
					['MAX_AIRCRAFT_FOR_RECONNAISSANCE'] = 2,
					['MAX_AIRCRAFT_FOR_INTERCEPT'] = 2,
					['ESCORT_NUMBER_MULTIPLIER'] = 3,
					['SCORE_INFLUENCE_ROUTE_THREAT'] = 1,
					['MAX_AIRCRAFT_FOR_BOMBER'] = 1,
					['MINIMUM_VALUE_OF_AIR_THREAT'] = 0.5,
					['MAX_AIRCRAFT_FOR_CAP'] = 4,
					['MINIMUM_REQUESTED_AIRCRAFT_FOR_STRIKE'] = 2,
					['MAX_AIRCRAFT_FOR_SWEEP'] = 4,
					['MAX_AIRCRAFT_FOR_ESCORT'] = 4,
					['MAX_AIRCRAFT_FOR_OTHER'] = 1,
					['MULTIPLIER_TARGET_DISTANCE_FOR_EVALUTATION_COMPUTING_ROUTE'] = 1.5,
					['FACTOR_FOR_REDUCE_SCORE'] = 0.01,
				},
				['red'] = {
					['UNIT_SERVICEABILITY'] = 0.8,
					['MIN_PERCENTAGE_FOR_ESCORT'] = 0.75,
					['FACTOR_FOR_REDUCTION_AIR_THREAT'] = 0.5,
					['MULTIPLIER_TARGET_DISTANCE_FOR_EVALUTATION_UNIT_RANGE_LOADOUT'] = 2,
					['WEIGHT_SCORE_FOR_AIRCRAFT_COST'] = {
						['Fighter'] = 0.3,
						['Refueler'] = 0.1,
						['Bomber'] = 0.2,
						['Transporter'] = 0.1,
						['AWACS'] = 0.1,
						['Reco'] = 0.2,
						['Attacker'] = 0.5,
						['Helicopter'] = 0.2,
					},
					['MAX_AIRCRAFT_FOR_STRIKE'] = 4,
					['WEIGHT_SCORE_FOR_LOADOUT_COST'] = {
						['Strike'] = 0.3,
						['Anti-ship Strike'] = 0.1,
						['Escort'] = 0.3,
						['Reconnaissance'] = 0.1,
						['SEAD'] = 0.1,
						['CAP'] = 0.4,
						['Fighter Sweep'] = 0.2,
						['Intercept'] = 0.2,
					},
					['MIN_TOTAL_AIR_THREAT_FOR_ESCORT_SUPPORT'] = 0.5,
					['MAX_AIRCRAFT_FOR_RECONNAISSANCE'] = 2,
					['MAX_AIRCRAFT_FOR_INTERCEPT'] = 2,
					['ESCORT_NUMBER_MULTIPLIER'] = 3,
					['SCORE_INFLUENCE_ROUTE_THREAT'] = 1,
					['MAX_AIRCRAFT_FOR_BOMBER'] = 1,
					['MINIMUM_VALUE_OF_AIR_THREAT'] = 0.5,
					['MAX_AIRCRAFT_FOR_CAP'] = 4,
					['MINIMUM_REQUESTED_AIRCRAFT_FOR_STRIKE'] = 2,
					['MAX_AIRCRAFT_FOR_SWEEP'] = 4,
					['MAX_AIRCRAFT_FOR_ESCORT'] = 4,
					['MAX_AIRCRAFT_FOR_OTHER'] = 1,
					['MULTIPLIER_TARGET_DISTANCE_FOR_EVALUTATION_COMPUTING_ROUTE'] = 1.5,
					['FACTOR_FOR_REDUCE_SCORE'] = 0.01,
				},
				['MIN_FOG_VISIBILITY'] = 5000,
				['BOMBERS_RECO'] = {
					[1] = 'S-3B',
					[2] = 'F-117A',
					[3] = 'B-1B',
					[4] = 'B-52H',
					[5] = 'Tu-22M3',
					[6] = 'Tu-95MS',
					[7] = 'Tu-142',
					[8] = 'Tu-160',
					[9] = 'MiG-25RBT',
				},
				['MIN_CLOUD_EIGHT_ABOVE_AIRBASE'] = 333,
				['MIN_CLOUD_DENSITY'] = 0.8,
			},
			['ATO_ThreatEvaluation'] = {
				['LARGE_AAA_SAM_FIXEDPOS_RILEVABILITY'] = 0.9,
				['MIN_ASSET_FOR_COMPUTE_LEVEL_INTERCEPT'] = 3,
				['LARGE_SHIP_RILEVABILITY'] = 0.95,
				['SMALL_AAA_SAM_IR_VEHICLE_RILEVABILITY'] = 0.4,
				['GROUND_THREAT_RILEVABILITY_BLUE_GROUND_CAPACITY'] = 1,
				['GROUND_THREAT_RILEVABILITY_RED_AIR_CAPACITY'] = 1,
				['GROUND_THREAT_RILEVABILITY_RED_GROUND_CAPACITY'] = 1,
				['SMALL_AAA_SAM_RADAR_VEHICLE_RILEVABILITY'] = 0.5,
				['MIN_ASSET_FOR_COMPUTE_LEVEL_CAP'] = 3,
				['SMALL_SHIP_RILEVABILITY'] = 0.7,
				['MEDIUM_AAA_SAM_FIXEDPOS_RILEVABILITY'] = 0.8,
				['SMALL_AAA_SAM_FIXEDPOS_RILEVABILITY'] = 0.6,
				['MEDIUM_AAA_SAM_IR_VEHICLE_RILEVABILITY'] = 0.6,
				['LARGE_SAM_VEHICLE_RILEVABILITY'] = 0.8,
				['MEDIUM_AAA_SAM_RADAR_VEHICLE_RILEVABILITY'] = 0.7,
				['MAN_SAM_RILEVABILITY'] = 0.2,
				['GROUND_THREAT_RILEVABILITY_BLUE_AIR_CAPACITY'] = 1,
				['MEDIUM_SHIP_RILEVABILITY'] = 0.8,
			},
			['SCORE_TASK_FACTOR'] = {
				['blue'] = {
					['Strike'] = {
						['hard'] = 1,
						['SAM'] = 1,
						['Bridge'] = 1,
						['armor'] = 1,
						['soft'] = 1,
						['Structure'] = 1,
						['Parked Aircraft'] = 1,
					},
					['Fighter Sweep'] = 1,
					['Anti-ship Strike'] = 1,
					['Intercept'] = 1,
					['AWACS'] = 1,
					['SEAD'] = 1,
					['Escort'] = 1,
					['Laser Illumination'] = 1,
					['CAP'] = 1,
					['Refueling'] = 1,
					['Reconnaissance'] = 1,
					['Transport'] = 1,
				},
				['red'] = {
					['Strike'] = {
						['hard'] = 1,
						['SAM'] = 1,
						['Bridge'] = 1,
						['armor'] = 1,
						['soft'] = 1,
						['Structure'] = 1,
						['Parked Aircraft'] = 1,
					},
					['Fighter Sweep'] = 1,
					['Anti-ship Strike'] = 1,
					['Intercept'] = 1,
					['AWACS'] = 1,
					['SEAD'] = 1,
					['Escort'] = 1,
					['Laser Illumination'] = 1,
					['CAP'] = 1,
					['Refueling'] = 1,
					['Reconnaissance'] = 1,
					['Transport'] = 1,
				},
			},
			['DC_LoadoutsAssignment'] = {
				['CRUISE_PARAM'] = {
					['blue'] = {
						['bomber'] = {
							['normal'] = {
								['min_hCruise'] = 2000,
								['min_vCruise_TAS'] = 111.11111111111,
								['max_hCruise'] = 8999,
								['max_vCruise_TAS'] = 166.66666666667,
							},
							['high'] = {
								['min_hCruise'] = 9000,
								['min_vCruise_TAS'] = 97.222222222222,
								['max_hCruise'] = 12000,
								['max_vCruise_TAS'] = 125,
							},
							['low'] = {
								['min_hCruise'] = 100,
								['min_vCruise_TAS'] = 125,
								['max_hCruise'] = 1999,
								['max_vCruise_TAS'] = 152.77777777778,
							},
							['supersonic'] = {
								['min_hCruise'] = 200,
								['min_vCruise_TAS'] = 416.66666666667,
								['max_hCruise'] = 12000,
								['max_vCruise_TAS'] = 555.55555555556,
							},
						},
						['refueler'] = {
							['normal'] = {
								['min_hCruise'] = 7000,
								['min_vCruise_TAS'] = 80.555555555556,
								['max_hCruise'] = 10000,
								['max_vCruise_TAS'] = 91.666666666667,
							},
							['low'] = {
								['min_hCruise'] = 2000,
								['min_vCruise_TAS'] = 80.555555555556,
								['max_hCruise'] = 6999,
								['max_vCruise_TAS'] = 88.888888888889,
							},
						},
						['transporter'] = {
							['normal'] = {
								['min_hCruise'] = 4500,
								['min_vCruise_TAS'] = 102.77777777778,
								['max_hCruise'] = 10000,
								['max_vCruise_TAS'] = 138.88888888889,
							},
						},
						['recon'] = {
							['normal'] = {
								['min_hCruise'] = 4500,
								['min_vCruise_TAS'] = 111.11111111111,
								['max_hCruise'] = 10000,
								['max_vCruise_TAS'] = 194.44444444444,
							},
						},
						['attacker'] = {
							['normal'] = {
								['min_hCruise'] = 1000,
								['min_vCruise_TAS'] = 125,
								['max_hCruise'] = 7000,
								['max_vCruise_TAS'] = 250,
							},
							['low'] = {
								['min_hCruise'] = 100,
								['min_vCruise_TAS'] = 111.11111111111,
								['max_hCruise'] = 999,
								['max_vCruise_TAS'] = 138.88888888889,
							},
						},
						['AWACS'] = {
							['normal'] = {
								['min_hCruise'] = 9000,
								['min_vCruise_TAS'] = 102.77777777778,
								['max_hCruise'] = 10000,
								['max_vCruise_TAS'] = 138.88888888889,
							},
						},
					},
					['red'] = {
						['bomber'] = {
							['normal'] = {
								['min_hCruise'] = 2000,
								['min_vCruise_TAS'] = 111.11111111111,
								['max_hCruise'] = 8999,
								['max_vCruise_TAS'] = 166.66666666667,
							},
							['high'] = {
								['min_hCruise'] = 9000,
								['min_vCruise_TAS'] = 105.55555555556,
								['max_hCruise'] = 12000,
								['max_vCruise_TAS'] = 130.55555555556,
							},
							['low'] = {
								['min_hCruise'] = 100,
								['min_vCruise_TAS'] = 102.77777777778,
								['max_hCruise'] = 1999,
								['max_vCruise_TAS'] = 125,
							},
							['supersonic'] = {
								['min_hCruise'] = 200,
								['min_vCruise_TAS'] = 416.66666666667,
								['max_hCruise'] = 12000,
								['max_vCruise_TAS'] = 555.55555555556,
							},
						},
						['refueler'] = {
							['normal'] = {
								['min_hCruise'] = 7000,
								['min_vCruise_TAS'] = 80.555555555556,
								['max_hCruise'] = 10000,
								['max_vCruise_TAS'] = 91.666666666667,
							},
							['low'] = {
								['min_hCruise'] = 2000,
								['min_vCruise_TAS'] = 80.555555555556,
								['max_hCruise'] = 6999,
								['max_vCruise_TAS'] = 91.666666666667,
							},
						},
						['transporter'] = {
							['normal'] = {
								['min_hCruise'] = 4500,
								['min_vCruise_TAS'] = 102.77777777778,
								['max_hCruise'] = 10000,
								['max_vCruise_TAS'] = 138.88888888889,
							},
						},
						['recon'] = {
							['normal'] = {
								['min_hCruise'] = 4500,
								['min_vCruise_TAS'] = 125,
								['max_hCruise'] = 10000,
								['max_vCruise_TAS'] = 166.66666666667,
							},
						},
						['attacker'] = {
							['normal'] = {
								['min_hCruise'] = 1000,
								['min_vCruise_TAS'] = 125,
								['max_hCruise'] = 7000,
								['max_vCruise_TAS'] = 250,
							},
							['low'] = {
								['min_hCruise'] = 100,
								['min_vCruise_TAS'] = 111.11111111111,
								['max_hCruise'] = 999,
								['max_vCruise_TAS'] = 152.77777777778,
							},
						},
						['AWACS'] = {
							['normal'] = {
								['min_hCruise'] = 9000,
								['min_vCruise_TAS'] = 102.77777777778,
								['max_hCruise'] = 10000,
								['max_vCruise_TAS'] = 138.88888888889,
							},
						},
					},
				},
				['PERCENTAGE_RANGE_FOR_STANDOFF_SETUP'] = {
					['Rockets'] = 0.6,
					['ASM'] = 0.7,
				},
				['ALTITUDE_ATTACK'] = {
					['Rockets'] = {
						['min'] = 50,
						['max'] = 1000,
					},
					['ASM'] = {
						['min'] = 200,
						['max'] = 6000,
					},
				},
				['ESCORT_DISTANCE_OVERRIDE'] = {
					['escort_bomber'] = {
						['min'] = 10000,
						['max'] = 20000,
					},
					['escort_sead_bomber'] = {
						['min'] = 20000,
						['max'] = 30000,
					},
					['escort_attacker'] = {
						['min'] = 7000,
						['max'] = 12000,
					},
					['escort_sead_attacker'] = {
						['min'] = 15000,
						['max'] = 25000,
					},
				},
				['MIN_EFFICIENCY_WEAPON_ATTRIBUTE'] = 0.01,
				['ACTIVATE_STANDOFF_SETUP'] = true,
				['ANGLE_OF_DESCENT_IN_GROUND_ATTACK'] = {
					['Rockets'] = {
						['min'] = 20,
						['max'] = 40,
						['med'] = 30,
					},
					['ASM'] = {
						['min'] = 10,
						['max'] = 35,
						['med'] = 25,
					},
				},
				['WEIGHT_MISSILE_A2A_MANOUVRABILITY'] = 0.2,
				['WEIGHT_MISSILE_A2A_RELIABILITY'] = 0.3,
				['FIREPOWER_FOR_AA_TARGETS'] = {
					['blue'] = {
						['CAP'] = {
							['min'] = 2,
							['max'] = 5,
						},
						['Fighter Sweep'] = {
							['min'] = 4,
							['max'] = 7,
						},
						['Escort'] = {
							['min'] = 3,
							['max'] = 5,
						},
						['Intercept'] = {
							['min'] = 3,
							['max'] = 6,
						},
					},
					['red'] = {
						['CAP'] = {
							['min'] = 2,
							['max'] = 5,
						},
						['Fighter Sweep'] = {
							['min'] = 4,
							['max'] = 7,
						},
						['Escort'] = {
							['min'] = 3,
							['max'] = 5,
						},
						['Intercept'] = {
							['min'] = 3,
							['max'] = 6,
						},
					},
				},
				['ESCORT_TIME_FOR_DISTANCE_OVERRIDE'] = {
					['escort_bomber'] = 1500,
					['escort_sead_bomber'] = 1200,
					['escort_attacker'] = 600,
					['escort_sead_attacker'] = 900,
				},
				['FIREPOWER_ROUNDED_COMPUTATION'] = 0.01,
				['ESCORT_ALTITUDE_OVERRIDE'] = {
					['escort_bomber'] = {
						['min'] = 300,
						['max'] = 1000,
					},
					['escort_sead_bomber'] = {
						['min'] = 500,
						['max'] = 1200,
					},
					['escort_attacker'] = {
						['min'] = 200,
						['max'] = 800,
					},
					['escort_sead_attacker'] = {
						['min'] = 300,
						['max'] = 800,
					},
				},
				['FACTOR_FOR_CALCULATED_TARGET_FIREPOWER_MAX'] = 1.1,
				['FIREPOWER_ROUNDED_ASSIGNEMENT'] = 0.1,
				['MAX_EFFICIENCY_WEAPON_ATTRIBUTE'] = 999999999,
			},
		},
		['winner'] = {
			['air'] = 'blue',
			['ground'] = 'blue',
			['ship'] = 'blue',
		},
		['directive_executed'] = {
			['blue'] = {
				[1] = 'restore air default condition',
				[2] = 'reset priority for all operations',
				[3] = 'restore global default condition',
				[4] = 'reset priority for all operations',
			},
			['red'] = {
				[1] = 'restore air default condition',
				[2] = 'reset priority for all operations',
				[3] = 'restore global default condition',
				[4] = 'reset priority for all operations',
			},
		},
		['mission'] = 1,
	},
}
