oob_air = {
	['blue'] = {
		[1] = {
			['number'] = 30,
			['type'] = 'AJS37',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Sweden',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['name'] = 'F21',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[2] = {
			['number'] = 8,
			['type'] = 'F-16C_50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Laser Illumination'] = true,
				['SEAD'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 1.5,
				['Fighter Sweep'] = 0.2,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['Anti-ship Strike'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = '13 TFS',
			['livery'] = '13th_Fighter_Squadron',
			['base'] = 'Senaki-Kolkhi',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
		},
		[3] = {
			['number'] = 6,
			['type'] = 'F-15E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
			['name'] = '335 TFS',
			['livery'] = '335th Fighter SQN (SJ)',
			['base'] = 'Vaziani',
		},
		[4] = {
			['number'] = 4,
			['type'] = 'AV8BNA',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['SEAD'] = false,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[100] = 'vma-311d',
			},
			['player'] = false,
			['name'] = 'VMA 311',
			['livery'] = 'vma-311',
			['sidenumber'] = {
				[1] = 100,
				[2] = 103,
			},
			['base'] = 'LHA_Tarawa',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
		},
		[5] = {
			['number'] = 30,
			['inactive'] = true,
			['name'] = 'VMA 331',
			['type'] = 'AV8BNA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['base'] = 'Reserves',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
		},
		[6] = {
			['number'] = 30,
			['type'] = 'M-2000C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'France',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['name'] = 'EC 2/12',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[7] = {
			['number'] = 24,
			['type'] = 'F-16C_50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = 'R/13 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[8] = {
			['number'] = 4,
			['type'] = 'KC-135',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '801 ARS',
			['livery'] = 'Standard USAF',
			['base'] = 'Senaki-Kolkhi',
		},
		[9] = {
			['number'] = 16,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[100] = 'vf-101 red',
				[105] = 'vf-101 grim reapers low vis',
				[111] = 'vf-101 dark',
			},
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 2,
				['Intercept'] = 2,
			},
			['player'] = false,
			['name'] = 'VF-101',
			['livery'] = {
				[1] = 'vf-101 grim reapers low vis',
				[2] = 'vf-101 dark',
			},
			['sidenumber'] = {
				[1] = 100,
				[2] = 115,
			},
			['base'] = 'CVN-71 Theodore Roosevelt',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[10] = {
			['number'] = 30,
			['type'] = 'F-14B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 30,
			},
			['name'] = 'R/VF-101',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[11] = {
			['number'] = 18,
			['type'] = 'F-15C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = 'R/58 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[12] = {
			['number'] = 8,
			['type'] = 'M-2000C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'France',
			['tasks'] = {
				['Strike'] = false,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 0.4,
				['Fighter Sweep'] = 1,
				['Escort'] = 1.2,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 2,
			},
			['player'] = false,
			['name'] = 'EC 1/12',
			['livery'] = {
				[2] = 'AdA 1-12 Cambresis 103-LB',
				[3] = 'AdA 1-12 Cambresis 103-YD',
				[1] = 'AdA 1-12 Cambresis 103-KN',
				[4] = 'AdA 1-12 Cambresis 103-YE',
				[5] = 'AdA 1-12 Cambresis 103-YF',
			},
			['base'] = 'Kutaisi',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
		},
		[13] = {
			['number'] = 28,
			['type'] = 'F/A-18C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 28,
			},
			['name'] = 'R/VFA-106',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[14] = {
			['number'] = 12,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 400,
				[2] = 429,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '174 ARW',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
		},
		[15] = {
			['number'] = 8,
			['type'] = 'F-15C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1,
				['CAP'] = 2,
				['Intercept'] = 2,
			},
			['player'] = false,
			['name'] = '58 TFS',
			['livery'] = '58th Fighter SQN (EG)',
			['base'] = 'Vaziani',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
		},
		[16] = {
			['number'] = 3,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '171 ARW',
			['livery'] = '',
			['base'] = 'Batumi',
		},
		[17] = {
			['number'] = 8,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 600,
				[2] = 609,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = 'VAW-125',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
		},
		[18] = {
			['number'] = 4,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '174 ARW',
			['livery'] = '',
			['base'] = 'Tbilissi-Lochini',
		},
		[19] = {
			['number'] = 3,
			['type'] = 'E-3A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'High',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 3,
			},
			['name'] = '7 ACCS',
			['livery'] = 'usaf standard',
			['base'] = 'Kutaisi',
		},
		[20] = {
			['number'] = 6,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/174 ARW',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
		},
		[21] = {
			['number'] = 4,
			['type'] = 'F-117A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '417 TFS',
			['livery'] = 'usaf standard',
			['base'] = 'Soganlug',
		},
		[22] = {
			['number'] = 9,
			['type'] = 'KC135MPRS',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/171 ARW',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 9,
			},
		},
		[23] = {
			['number'] = 6,
			['type'] = 'KC-135',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/801 ARS',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 6,
			},
		},
		[24] = {
			['number'] = 16,
			['type'] = 'FA-18C_hornet',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['SEAD'] = true,
				['Anti-ship Strike'] = true,
				['CAP'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['liveryModex'] = {
				[200] = 'vfa-106 high visibility',
			},
			['tasksCoef'] = {
				['Strike'] = 2.5,
				['Fighter Sweep'] = 0.1,
				['Escort'] = 0.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 2,
				['Anti-ship Strike'] = 2,
				['CAP'] = 0.2,
				['Intercept'] = 1,
			},
			['player'] = false,
			['name'] = 'VFA-106',
			['livery'] = 'vfa-106',
			['sidenumber'] = {
				[1] = 200,
				[2] = 215,
			},
			['base'] = 'CVN-71 Theodore Roosevelt',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 16,
			},
		},
		[25] = {
			['number'] = 12,
			['type'] = 'AJS37',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Sweden',
			['tasks'] = {
				['Strike'] = true,
				['Fighter Sweep'] = false,
				['Escort'] = false,
				['CAP'] = false,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 3,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['player'] = true,
			['name'] = 'F7',
			['livery'] = {
				[1] = '#4 Splinter F7 Skaraborgs Flygflottilj 76',
			},
			['base'] = 'Sukhumi',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
		},
		[26] = {
			['number'] = 18,
			['type'] = 'F-15E',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = 'R/335 TFS',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[27] = {
			['number'] = 12,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
				['Refueling'] = true,
			},
			['skill'] = 'High',
			['sidenumber'] = {
				[1] = 430,
				[2] = 450,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '175 ARW',
			['livery'] = '',
			['base'] = 'CVN-71 Theodore Roosevelt',
		},
		[28] = {
			['number'] = 10,
			['type'] = 'S-3B Tanker',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/174 ARW',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 10,
			},
		},
		[29] = {
			['number'] = 1,
			['type'] = 'E-2C',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'USA',
			['tasks'] = {
			},
			['skill'] = 'High',
			['inactive'] = true,
			['name'] = 'R/VAW-125',
			['base'] = 'Reserves',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
		},
	},
	['red'] = {
		[1] = {
			['number'] = 24,
			['type'] = 'Su-27',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '3./31.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[2] = {
			['number'] = 1,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '3.OSAP',
			['livery'] = {
				[1] = 'Aeroflot',
				[2] = 'RF Air Force',
			},
			['base'] = 'Beslan',
		},
		[3] = {
			['number'] = 24,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '3./19.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[4] = {
			['number'] = 8,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
				['Laser Illumination'] = true,
			},
			['skill'] = 'high',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1.5,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '1./41.IAP',
			['livery'] = '',
			['base'] = 'Mineralnye-Vody',
		},
		[5] = {
			['number'] = 24,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '2./14.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[6] = {
			['number'] = 18,
			['type'] = 'Tu-22M3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = 'R./61.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[7] = {
			['number'] = 12,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1.5,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 2,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '1./14.IAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Mozdok',
		},
		[8] = {
			['number'] = 4,
			['type'] = 'A-50',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['AWACS'] = true,
			},
			['skill'] = 'high',
			['sidenumber'] = {
				[1] = 800,
				[2] = 805,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 4,
			},
			['name'] = '2457 SDRLO',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Nalchik',
		},
		[9] = {
			['number'] = 12,
			['type'] = 'Su-25T',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1.5,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '1./17.IAP',
			['livery'] = '',
			['base'] = 'Mozdok',
		},
		[10] = {
			['number'] = 8,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1.5,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '2./19.IAP',
			['livery'] = '',
			['base'] = 'Nalchik',
		},
		[11] = {
			['number'] = 12,
			['type'] = 'MiG-29A',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 2,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1,
				['Intercept'] = 1.5,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '1./19.IAP',
			['livery'] = '',
			['base'] = 'Beslan',
		},
		[12] = {
			['number'] = 1,
			['type'] = 'An-26B',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Transport'] = true,
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 1,
			},
			['name'] = '2.OSAP',
			['livery'] = {
				[1] = 'Aeroflot',
				[2] = 'RF Air Force',
			},
			['base'] = 'Sochi-Adler',
		},
		[13] = {
			['number'] = 18,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = 'R./41.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[14] = {
			['number'] = 18,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'high',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 18,
			},
			['name'] = 'R./81.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
		[15] = {
			['number'] = 12,
			['type'] = 'MiG-31',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'High',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 2,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 12,
			},
			['name'] = '790.IAP',
			['livery'] = 'af standard',
			['base'] = 'Mozdok',
		},
		[16] = {
			['number'] = 10,
			['type'] = 'Su-27',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['CAP'] = true,
				['Fighter Sweep'] = true,
				['Escort'] = true,
				['Intercept'] = true,
			},
			['skill'] = 'Random',
			['tasksCoef'] = {
				['Strike'] = 1,
				['Fighter Sweep'] = 1.5,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['CAP'] = 1.5,
				['Intercept'] = 2,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 10,
			},
			['name'] = '1./31.IAP',
			['livery'] = '',
			['base'] = 'Mineralnye-Vody',
		},
		[17] = {
			['number'] = 8,
			['type'] = 'Tu-22M3',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
			},
			['skill'] = 'high',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1.5,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '1./61.IAP',
			['livery'] = {
				[1] = '',
			},
			['base'] = 'Maykop-Khanskaya',
		},
		[18] = {
			['number'] = 8,
			['type'] = 'Su-24M',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['country'] = 'Russia',
			['tasks'] = {
				['Strike'] = true,
				['Anti-ship Strike'] = true,
				['SEAD'] = true,
			},
			['skill'] = 'high',
			['tasksCoef'] = {
				['Strike'] = 2,
				['Fighter Sweep'] = 1,
				['Escort'] = 1,
				['Laser Illumination'] = 1,
				['SEAD'] = 1,
				['Anti-ship Strike'] = 1.5,
				['CAP'] = 1,
				['Intercept'] = 1,
			},
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 8,
			},
			['name'] = '1./81.IAP',
			['livery'] = '',
			['base'] = 'Maykop-Khanskaya',
		},
		[19] = {
			['number'] = 24,
			['type'] = 'Su-25T',
			['score'] = {
				['kills_ship'] = 0,
				['kills_air'] = 0,
				['kills_ground'] = 0,
			},
			['tasks'] = {
			},
			['skill'] = 'Random',
			['roster'] = {
				['lost'] = 0,
				['damaged'] = 0,
				['ready'] = 24,
			},
			['name'] = '2./17.IAP',
			['base'] = 'Reserves',
			['inactive'] = true,
		},
	},
}
